server:
  port: 8080

spring:
  application:
    name: health-backend

  datasource:
    url: jdbc:mysql://localhost:3306/health_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: tty20031015
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.health.entity

logging:
  level:
    com.health.mapper: debug